# syntax=docker/dockerfile:1   

FROM python:3.9-slim-buster         # change the version as per requirement

WORKDIR /python-docker

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .

CMD [ "python", "app.py"]


from flask import Flask
app = Flask(__name__)
@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"
